---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu-20.04
    image: 'antmelekhin/docker-systemd:ubuntu-20.04'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/lib/containerd'
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: rockylinux8
    image: 'antmelekhin/docker-systemd:rockylinux-8'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/lib/containerd'
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: fedora-39
    image: 'antmelekhin/docker-systemd:fedora-39'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/lib/containerd'
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
